[images]
remote_images = [
  "https://source.unsplash.com/.*",
  "https://images.unsplash.com/.*",
  "https://ext.same-assets.com/.*",
  "https://ugc.same-assets.com/.*",
  "^(?:https:\\/\\/source\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:https:\\/\\/images\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:https:\\/\\/ext\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:https:\\/\\/ugc\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http(?:s)?:\\/\\/source\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http(?:s)?:\\/\\/images\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http(?:s)?:\\/\\/ext\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
  "^(?:http(?:s)?:\\/\\/ugc\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
]

[build]
command = "bun run build"
publish = ".next"

  [build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/_next/static/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]

  [context.production]

    [context.production.images]
    remote_images = [
      "https://source.unsplash.com/.*",
      "https://images.unsplash.com/.*",
      "https://ext.same-assets.com/.*",
      "https://ugc.same-assets.com/.*",
      "^(?:https:\\/\\/source\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/images\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/ext\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/ugc\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/source\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/images\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/ext\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/ugc\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

    [[context.production.headers]]
    for = "/_next/static/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.main]

    [context.main.images]
    remote_images = [
      "https://source.unsplash.com/.*",
      "https://images.unsplash.com/.*",
      "https://ext.same-assets.com/.*",
      "https://ugc.same-assets.com/.*",
      "^(?:https:\\/\\/source\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/images\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/ext\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:https:\\/\\/ugc\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/source\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/images\\.unsplash\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/ext\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/ugc\\.same-assets\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

    [[context.main.headers]]
    for = "/_next/static/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"